/* Generated By:JavaCC: Do not edit this line. ej1Constants.java */
package FISQL.Interprete.XML;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ej1Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int abre = 1;
  /** RegularExpression Id. */
  int cierra = 2;
  /** RegularExpression Id. */
  int slash = 3;
  /** RegularExpression Id. */
  int igual = 4;
  /** RegularExpression Id. */
  int id = 5;
  /** RegularExpression Id. */
  int num = 6;
  /** RegularExpression Id. */
  int script = 7;
  /** RegularExpression Id. */
  int todo = 8;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"<\"",
    "\">\"",
    "\"</\"",
    "\"=\"",
    "<id>",
    "<num>",
    "<script>",
    "<todo>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"\\t\"",
  };

}
