/* Generated By:JavaCC: Do not edit this line. ej1Constants.java */
package FISQL.Interprete.XML;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ej1Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int abre = 6;
  /** RegularExpression Id. */
  int cierra = 7;
  /** RegularExpression Id. */
  int slash = 8;
  /** RegularExpression Id. */
  int id = 9;
  /** RegularExpression Id. */
  int todo = 10;
  /** RegularExpression Id. */
  int num = 11;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"\\t\"",
    "\"<\"",
    "\">\"",
    "\"</\"",
    "<id>",
    "<todo>",
    "<num>",
  };

}
