/* Generated By:JavaCC: Do not edit this line. ej1Constants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ej1Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMA = 1;
  /** RegularExpression Id. */
  int ENTERO = 2;
  /** RegularExpression Id. */
  int CARATER = 3;
  /** RegularExpression Id. */
  int ID = 4;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\",\"",
    "\"int\"",
    "\"char\"",
    "<ID>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"\\t\"",
  };

}
