/* Generated By:JavaCC: Do not edit this line. ej1Constants.java */
package FISQL.Interprete.Lenguaje;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ej1Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int OR = 1;
  /** RegularExpression Id. */
  int NOT = 2;
  /** RegularExpression Id. */
  int AND = 3;
  /** RegularExpression Id. */
  int ID = 4;
  /** RegularExpression Id. */
  int IGUALIGUAL = 5;
  /** RegularExpression Id. */
  int NOTIGUAL = 6;
  /** RegularExpression Id. */
  int MAYORQUE = 7;
  /** RegularExpression Id. */
  int MENORQUE = 8;
  /** RegularExpression Id. */
  int MENORIGUAL = 9;
  /** RegularExpression Id. */
  int MAYORIGUAL = 10;
  /** RegularExpression Id. */
  int MAS = 11;
  /** RegularExpression Id. */
  int MENOS = 12;
  /** RegularExpression Id. */
  int POR = 13;
  /** RegularExpression Id. */
  int DIV = 14;
  /** RegularExpression Id. */
  int ELEVA = 15;
  /** RegularExpression Id. */
  int NUM = 16;
  /** RegularExpression Id. */
  int FECHA = 17;
  /** RegularExpression Id. */
  int FECHA_HORA = 18;
  /** RegularExpression Id. */
  int DECIMAL = 19;
  /** RegularExpression Id. */
  int CADENA = 20;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"||\"",
    "\"!\"",
    "\"&&\"",
    "<ID>",
    "\"==\"",
    "\"!=\"",
    "\">\"",
    "\"<\"",
    "\"<=\"",
    "\">=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"^\"",
    "<NUM>",
    "<FECHA>",
    "<FECHA_HORA>",
    "<DECIMAL>",
    "<CADENA>",
    "\" \"",
    "\"\\r\\n\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 26>",
    "<token of kind 27>",
  };

}
